# Generated by Django 3.2.3 on 2025-03-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0002_alter_seed_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='image',
            field=models.ImageField(blank=True, upload_to='seeds/', verbose_name='Картинка'),
        ),
    ]
