# Generated by Django 3.2.3 on 2025-03-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0003_alter_seed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='translit',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='type',
            name='translit',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
